"""Core data models and enums for Predictive Field Memory system.

This module implements the foundational data structures for the cognitive field-based
memory architecture, supporting the four-layer memory organization:
- Layer 1: Exposure Events Layer (raw observational data)
- Layer 2: State Field Layer (currently activated cognitive field)
- Layer 3: Operator Memory Layer (learned transformation patterns)
- Layer 4: Transition Memory Layer (partial-to-complete state transitions)

Requirements: 1.6, 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple

import numpy as np


# ============================================================================
# Enums
# ============================================================================


class OperatorType(Enum):
    """Types of state transformation operators in Layer 3.
    
    Each operator type represents a different kind of transformation pattern
    that the system learns from experience.
    """
    COMPLETION = "completion"
    REPAIR = "repair"
    EXPLANATION = "explanation"
    COMPARISON = "comparison"
    TRANSFORMATION = "transformation"
    COMPOSITION = "composition"


class ConflictType(Enum):
    """Types of conflicts that can occur in the cognitive field.
    
    Conflicts increase field energy and drive candidate generation toward
    tension reduction.
    """
    CONTRADICTION = "contradiction"
    CONSTRAINT_VIOLATION = "constraint_violation"
    REPETITION = "repetition"


class TensionType(Enum):
    """Types of tension sources in the cognitive field.
    
    Tension indicates high field energy from incompleteness, conflicts,
    or unsatisfied goals. Candidate generation aims to reduce tension.
    """
    CONFLICT = "conflict"
    UNSATISFIED_GOAL = "unsatisfied_goal"
    INCOMPLETE_OUTPUT = "incomplete_output"


class CandidateSource(Enum):
    """Sources from which candidates can emerge.
    
    Candidates arise from different mechanisms in the field-based system:
    - Operator-based: Generated by applying learned operators
    - Transition-based: Generated from similar state transitions
    - Hybrid: Generated from combination of operators and transitions
    - Field dynamics: Generated directly from field resonance patterns
    """
    OPERATOR_BASED = "operator"
    TRANSITION_BASED = "transition"
    HYBRID = "hybrid"
    FIELD_DYNAMICS = "field_dynamics"


class ConvergenceReason(Enum):
    """Reasons why recursive stabilization converged or stopped.
    
    Indicates why the stabilization loop terminated, which helps diagnose
    generation quality and system behavior.
    """
    NOT_CONVERGED = "not_converged"
    ENERGY_MINIMUM = "energy_minimum"
    ENERGY_STABLE = "energy_stable"
    OUTPUT_COMPLETE = "output_complete"
    NO_CANDIDATES = "no_candidates"
    MAX_ITERATIONS = "max_iterations"


# ============================================================================
# Input/Output Data Structures
# ============================================================================


@dataclass
class InputContext:
    """Input context for field formation.
    
    Represents the input that triggers cognitive field activation across
    all memory layers. Used in Requirements 12.1 (query features), and
    supports optional goals and constraints for field dynamics.
    """
    query_text: str
    query_features: List[str] = None
    query_hv: np.ndarray = None
    modality: str = "text"
    domain: str = "general"
    partial_output: str = ""
    goals: Optional[List[str]] = None
    constraints: Optional[List[str]] = None
    metadata: Optional[Dict] = None
    
    def __post_init__(self):
        """Initialize optional fields with defaults."""
        if self.query_features is None:
            self.query_features = []
        if self.query_hv is None:
            self.query_hv = np.array([], dtype=np.uint64)
    
    @property
    def text(self) -> str:
        """Backward compatibility alias for query_text."""
        return self.query_text
    
    @classmethod
    def from_text(cls, text: str, **kwargs):
        """Create InputContext from text (backward compatibility)."""
        return cls(query_text=text, **kwargs)


@dataclass
class ConvergenceStats:
    """Statistics about convergence process.
    
    Tracks information about how and why the recursive stabilization
    loop converged, useful for analysis and debugging.
    """
    iterations: int
    final_energy: float
    energy_reduction: float
    convergence_reason: ConvergenceReason
    oscillation_detected: bool


@dataclass
class Candidate:
    """Generated output candidate that emerged from field tension.
    
    Represents a potential continuation that reduces field energy. Contains
    tracking information about what tension sources it addresses and how
    much energy reduction it provides.
    """
    # Content
    content: str
    tokens: List[str]
    
    # Energy analysis
    energy_reduction: float
    predicted_energy_after: float
    
    # Source tracking
    source: CandidateSource
    source_operators: List[str]  # Which operators contributed
    source_transitions: List[str]  # Which transitions contributed
    
    # Tension resolution
    tensions_addressed: List[TensionSource]
    tensions_resolved_count: int
    
    # Confidence
    confidence: float


# ============================================================================
# State Field Layer (Layer 2) Data Structures
# ============================================================================


@dataclass
class ConflictMarker:
    """Marker for a conflict in the cognitive field.
    
    Conflicts increase field energy and represent incompatibilities between
    activated memories, constraint violations, or repetition patterns.
    Requirement 12.5 specifies conflict markers with strengths.
    """
    conflict_id: str
    conflict_type: ConflictType
    involved_memories: List[str]
    strength: float
    description: str


@dataclass
class GoalState:
    """Active goal in the cognitive field.
    
    Goals guide candidate generation by defining what the field should
    achieve. Unsatisfied goals create tension that drives output generation.
    Requirement 12.6 specifies goal states with satisfaction levels.
    """
    goal_id: str
    goal_description: str
    satisfaction_level: float  # 0.0 to 1.0
    constraints: List[str]


@dataclass
class TensionSource:
    """Source of tension in the cognitive field.
    
    Tension indicates high field energy from incompleteness, conflicts, or
    unsatisfied goals. Candidates are generated to reduce these tension sources.
    Used by candidate emergence to guide generation.
    """
    type: TensionType  # conflict, unsatisfied_goal, incomplete_output
    location: str  # Where in the field
    strength: float
    description: str


@dataclass
class StateField:
    """The currently activated cognitive field (Layer 2).
    
    Represents the living cognitive state containing simultaneously activated
    memories, concepts, operators, conflicts, goals, and partial outputs.
    This is the core data structure for field-based dynamics.
    
    Requirements:
    - 12.1: query feature representations
    - 12.2: activated events with strengths
    - 12.3: activated concepts with strengths
    - 12.4: activated operators with strengths
    - 12.5: conflict markers with strengths
    - 12.6: goal states with satisfaction levels
    - 12.7: partial output representations
    """
    # Input representation
    query_features: List[str]
    query_hv: np.ndarray
    
    # Activated memories with strengths
    activated_events: Dict[str, float]  # event_id → activation
    activated_concepts: Dict[str, float]  # concept_id → activation
    activated_operators: Dict[str, float]  # operator_id → activation
    
    # Field dynamics
    conflict_markers: List[ConflictMarker]
    goal_states: List[GoalState]
    partial_outputs: List[str]
    
    # Resonance matrix
    resonance: Dict[Tuple[str, str], float] = field(default_factory=dict)  # (mem1, mem2) → resonance_strength
    
    # Energy state
    field_energy: Optional[FieldEnergy] = None
    
    # History for recursive updates
    previous_outputs: List[str] = field(default_factory=list)
    iteration: int = 0


@dataclass
class FieldEnergy:
    """Field energy decomposition for free energy minimization.
    
    Energy = conflicts - evidence
    Lower energy is more stable. Field dynamics drive toward lower energy states.
    
    Evidence sources (decrease energy):
    - Memory resonance: Activated memories support each other
    - Goal satisfaction: Goals are being satisfied
    - Constraint satisfaction: Constraints are met
    - Memory support: Strong backing from memory
    - Coherence: Internal consistency
    
    Conflict sources (increase energy):
    - Contradiction: Memories conflict
    - Constraint violation: Constraints violated
    - Repetition: Unwanted repetition
    - Incompleteness: Missing information
    - Goal conflict: Goals conflict with each other
    
    Requirement 1.6 specifies field energy computation from all state components.
    """
    # Total energy (conflicts - evidence)
    total: float
    
    # Components
    evidence: float
    conflicts: float
    
    # Detailed breakdown
    evidence_breakdown: Dict[str, float]  # source → contribution
    conflict_breakdown: Dict[str, float]  # source → contribution
    
    # Interpretation
    dominant_evidence_sources: List[str]
    dominant_conflict_sources: List[str]
    tension_level: float  # Normalized 0-1


# ============================================================================
# Operator Memory Layer (Layer 3) Data Structures
# ============================================================================


@dataclass
class StatePattern:
    """Abstract pattern that matches field states.
    
    Used by operators to determine when they are applicable to a given
    field state. Patterns can match based on features, concepts, 
    incompleteness markers, and active goals.
    
    Requirement 1.7 specifies operator storage with transformation patterns.
    """
    required_features: Set[str]
    required_concepts: Set[str]
    incompleteness_markers: List[str]
    goal_patterns: List[str]


@dataclass
class TransformationRule:
    """How to transform a matched state.
    
    Defines the transformation logic for converting partial states to
    complete states. Can be template-based, learned from transitions,
    or feature combination.
    
    Requirement 1.7 specifies transformation types within operators.
    """
    rule_type: str  # "template", "learned_transition", "feature_combination"
    parameters: Dict[str, Any]
    confidence_threshold: float


@dataclass
class OperatorRecord:
    """Learned state transformation operator (Layer 3).
    
    Represents a repeated transformation pattern abstracted from multiple
    exposures. Operators enable generalization beyond specific examples
    by capturing the structure of transformations.
    
    Requirements:
    - 1.7: Operator storage with types and transformation patterns
    - 4.1: Storage as state transformation operators
    - 4.2-4.6: Different operator types (explanation, repair, completion, etc.)
    """
    operator_id: str
    operator_type: OperatorType
    
    # Pattern matching
    pattern: StatePattern  # What field states this applies to
    preconditions: List[str]  # Required field properties
    
    # Transformation
    transformation: TransformationRule  # How to generate output
    completion_template: str
    
    # Statistics
    confidence: float
    usage_count: int
    success_rate: float
    generalization_level: int  # How abstract the operator is
    
    # Provenance
    induced_from: List[str]  # Transition IDs this was learned from
    timestamp: float


# ============================================================================
# Transition Memory Layer (Layer 4) Data Structures
# ============================================================================


@dataclass
class CompletionPattern:
    """Pattern of how a partial state was completed.
    
    Extracted from StateTransition, represents the abstract structure of
    completion that can be applied to similar partial states.
    
    Requirements:
    - 5.1-5.4: Partial-to-complete transitions across domains
    """
    # What was added to complete the state
    added_features: List[str]
    added_concepts: Set[str]
    
    # Completion characteristics
    completion_type: str  # "direct", "elaboration", "correction", "explanation"
    modality: str
    domain: str
    
    # HDC representation of completion
    completion_vector: np.ndarray
    
    # Confidence
    reliability: float


@dataclass
class StateTransition:
    """Partial-to-complete state transition (Layer 4).
    
    Stores a pair of (incomplete state, complete state) representing how
    the system learned to complete a particular type of incomplete state.
    NOT before/after pairs - specifically partial/complete pairs.
    
    Requirements:
    - 1.8: Storage of S_partial → S_complete pairs
    - 5.1: Transitions stored as S_partial → S_complete, not S_before → S_after
    - 5.2: Conversation turns as incomplete→completed context
    - 5.3: Code generation as incomplete→completed code
    - 5.4: Reasoning steps as incomplete→completed reasoning
    """
    transition_id: str
    
    # The incomplete → complete state pair
    partial_state: StateField
    complete_state: StateField
    
    # Difference representation
    completion_vector: np.ndarray  # HDC vector of what was added
    completion_features: List[str]
    
    # Context
    modality: str
    domain: str  # conversation, code, document, reasoning
    
    # Statistics
    timestamp: float
    relevance_count: int  # How often this transition was useful


# ============================================================================
# Persistence and Serialization Data Structures
# ============================================================================


@dataclass
class CognitiveFieldSnapshot:
    """Complete snapshot of cognitive field state for serialization.
    
    Contains all four memory layers plus configuration and statistics.
    Used for saving and loading the entire cognitive field state.
    
    Requirement 1.6 specifies complete field state representation.
    """
    version: str
    timestamp: float
    
    # Layer 1: Exposure Events (preserved PUHL structure)
    events: Dict[str, Any]  # EventRecord instances (from original PUHL)
    edges: Dict[Tuple[int, int], float]
    feature_to_id: Dict[str, int]
    id_to_feature: List[str]
    event_hv: Dict[str, np.ndarray]
    
    # Layer 3: Operator Memory
    operators: Dict[str, OperatorRecord]
    
    # Layer 4: Transition Memory
    transitions: Dict[str, StateTransition]
    
    # Statistics
    total_exposures: int
    total_operators_induced: int
    total_transitions_stored: int
    
    # Configuration
    window_size: int
    decay: float
    hdc_dimensions: int


# ============================================================================
# Constants for Energy Computation
# ============================================================================


# Evidence sources (decrease energy)
EVIDENCE_SOURCES = [
    "memory_resonance",      # Activated memories support each other
    "goal_satisfaction",     # Goals are being satisfied
    "constraint_satisfaction",  # Constraints are met
    "memory_support",        # Strong backing from memory
    "coherence",            # Internal consistency
]

# Conflict sources (increase energy)
CONFLICT_SOURCES = [
    "contradiction",         # Memories conflict
    "constraint_violation",  # Constraints violated
    "repetition",           # Unwanted repetition
    "incompleteness",       # Missing information
    "goal_conflict",        # Goals conflict with each other
]
